# do not touch this line
configVersion: 2

description: test gestures
keywords: test
name: gestureTest


screens:
  - - gestureLocation

services:
  gestureTest:
    engine: gesture
    type: palm

dataTypes:
  palmLocation:
    x: integer
    y: integer
    width: integer
    height: integer


widgets:
  gestureLocation:
    type: palmLocation
    keys:
      - x
      - y
      - width
      - height
    display: list-group
    label: 'Detected Palm Location'
