# do not touch this line
configVersion: 2

description: crosstalkProducerTest
keywords: Crosstalk Producer
name: crosstalkProducerTest

screens:
    - - globalScreen
      - specificScreen
      - eventScreen

dataTypes:
    globalEmitter:
        globalValue: integer
    specificEmitter:
        specificValue: string
    eventEmitter:
        eventFloat1: float
        eventFloat2: float

widgets:
    globalScreen:
        type: globalEmitter
        display: digit
        keys:
            - globalValue
        label: "Global Sent Value"
    specificScreen:
        type: specificEmitter
        display: digit
        keys:
            - specificValue
        label: "App Specific Sent Value"
    eventScreen:
        type: eventEmitter
        keys:
            - eventFloat1
            - eventFloat2
        display: list-group
        label: "Event Sent Value"
    
