# do not touch this line
configVersion: 2

description: test the sensors fool
name: sensorTest

sensors:
  - temperature
  - humidity
  - accelerometer
  - gyroscope
  - uv
  - pressure
  - altitude

screens:
  - - temperatureScreen

dataTypes:
  temperature: 
    value: float
  humidity: float
  accelerometer: float
  gyroscope:
    x: float
    y: float
    z: float
  uv: float
  pressure: float
  altitude: float

widgets:
  temperatureScreen:
    type: temperature
    key: value
    display: digit
    format: round
    label: temperature ºC
